### ISSUE TITLE
Getting undefined

### ISSUE THREAD

**Issue by jwhittle933** [jwosborn/Adapter-app#17]
# Getting Undefined
* Check this out when I select Norton 012 and Seminary Issue Dell Laptop

<img width="444" alt="screen shot 2019-02-23 at 11 40 54 am" src="https://user-images.githubusercontent.com/41909513/53289136-fd251f00-375f-11e9-9f8a-7be513050fab.png">

**Comment by jwosborn** [comment]
## This issue will go away when I make the switch from the Submit button to onChange. 
* Click submit (which the onChange will do automatically) and it goes away because NO adapter is needed for that combo. 
* Be advised there are probably other similar bugs when the lists are changed. Right now the onChange function changes target, but doesn't call the conditional to change needsAdapter in state which displays Positive or Negative. So whatever was up before remains until submit button is clicked and the conditional is run.
